### ISSUE TITLE
Add docker image pushing to CI

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygon/cdk-data-availability#16]

**Comment by vcastellm** [comment]
Can be automated using goreleaser, see https://github.com/0xPolygon/polygon-edge/blob/develop/.goreleaser.yml#L100-L134 as an example

**Comment by christophercampbell** [comment]
@arnaubennassar @vcastellm I've started a draft PR for this, but I'm not sure it is correct, just "cargo culted" it from other projects. I presume it'll need credentials to push to hermeznetwork docker repo
