### ISSUE TITLE
Db should be moved outside DAC node

### ISSUE THREAD

**Issue by RohanShrothrium** [0xPolygon/cdk-data-availability#32]
We are working on deploying CDKs and having the db as a part of the node would not work in production(maintained dbs are battle-tested). 
I haven't seen any activity on this repo in a while, so I could take this up if the team finds it important.

**Comment by arnaubennassar** [comment]
What do you mean by "having the db as a part of the node"? The DB is Postgres, and you can set up it as you please

**Comment by RohanShrothrium** [comment]
Aah my bad, I thought the Dockerfile exported the image as db+dac.
Closing it with this comment!
