### ISSUE TITLE
It is recommended to modify the findContractDeploymentBlock function to obtain the block number and call eth.HeaderByNumber.

### ISSUE THREAD

**Issue by phpxin** [0xPolygon/cdk-data-availability#65]
**`'r' value overflows uint256` is shown when starting DA program**

Then I used Delve to find the error out, and I saw this code thrown the error :

```
> github.com/0xPolygon/cdk-data-availability/synchronizer.findContractDeploymentBlock() ./synchronizer/init.go:51 (hits goroutine(1):1 total:1) (PC: 0x1143f63)
    46:		eth, err := ethclient.DialContext(ctx, url)
    47:		if err != nil {
    48:			return nil, err
    49:		}
    50:		latestBlock, err := eth.BlockByNumber(ctx, nil)
=>  51:		if err != nil {
    52:			return nil, err
    53:		}
    54:		firstBlock := findCode(ctx, eth, contract, 0, latestBlock.Number().Int64())
    55:		return big.NewInt(firstBlock), nil
    56:	}
(dlv) p err
error(*errors.errorString) *{
	s: "'r' value overflows uint256",}
(dlv) q
```

I fixed it by change 'eth.BlockByNumber' to 'eth.HeaderByNumber(ctx, nil)'

<img width="1119" alt="image" src="https://github.com/0xPolygon/cdk-data-availability/assets/11712603/4b30cec6-b87a-4d3f-81b2-a227cbf002aa">

When I got the error I am using branch 'v0.0.3', but I saw the default branch is still using 'eth.BlockByNumber'

**Comment by HONGYI-SD** [comment]
fix bug of  `'r' value overflows uint256 `  
update code like below:
![Uploading WX20240318-221007@2x.png…]()

**Comment by HONGYI-SD** [comment]
update code `firstBlock := findCode(ctx, eth, contract, 0, latestBlock.Number().Int64())` to `firstBlock := findCode(ctx, eth, contract, 0, latestBlock.Number.Int64())`

**Comment by cpucorecore** [comment]
i meet the same issue. thank for your fixing the problem

**Comment by christophercampbell** [comment]
Thanks, fix in review

**Comment by christophercampbell** [comment]
Fixed in main, will be included in next release.
